export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_PRODUCTS_BY_SLUG = "GET_PRODUCTS_BY_SLUG";
export const GET_PRODUCTS_LOADING = "GET_PRODUCTS_LOADING";
export const GET_PRODUCTS_DETAILS_LOADING = "GET_PRODUCTS_DETAILS_LOADING";

export const GET_SLIDERS = "GET_SLIDERS";
export const GET_SLIDERS_LOADING = "GET_SLIDERS_LOADING";

export const GET_CARTS = "GET_CARTS";
export const GET_CARTS_LOADING = "GET_CARTS_LOADING";
export const POST_CARTS_LOADING = "POST_CARTS_LOADING";
export const UPDATE_CARTS_LOADING = "UPDATE_CARTS_LOADING";
export const EMPTY_CART_MESSAGE = "EMPTY_CART_MESSAGE";
export const EMPTY_CART_DELETE_MESSAGE = "EMPTY_CART_DELETE_MESSAGE";
export const POST_CARTS_DATA = "POST_CARTS_DATA";
export const UPDATE_CARTS_DATA = "UPDATE_CARTS_DATA";
export const DELETE_CARTS_DATA = "DELETE_CARTS_DATA";

export const CHANGE_LOGIN_INPUT_FIELD = "CHANGE_LOGIN_INPUT_FIELD";
export const AUTH_LOGIN_CHECK = "AUTH_LOGIN_CHECK";
export const AUTH_GET_LOGIN_DATA = "AUTH_GET_LOGIN_DATA";
export const AUTH_POST_LOGOUT = "AUTH_POST_LOGOUT";
export const AUTH_REGISTER = "AUTH_REGISTER";
export const CHANGE_REGISTER_INPUT_FIELD = "CHANGE_REGISTER_INPUT_FIELD";
export const REGISTER_FIRST_STEP = "REGISTER_FIRST_STEP";
export const REGISTER_FIRST_STEP_LOADING = "REGISTER_FIRST_STEP_LOADING";

/**Vendor Register */
export const CHANGE_VENDOR_REGISTER_INPUT = "CHANGE_VENDOR_REGISTER_INPUT";
export const VENDOR_REGISTER_FIRST_STEP = "VENDOR_REGISTER_FIRST_STEP";
export const VENDOR_REGISTER = "VENDOR_REGISTER";
/** Vendors */
export const GET_VENDORS_LIST = "GET_VENDORS_LIST";
export const GET_VENDORS_LOADING = "GET_VENDORS_LOADING";

/** Brands */
export const GET_BRANDS_LIST = "GET_BRANDS_LIST";
export const GET_BRANDS_LOADING = "GET_BRANDS_LOADING";

/** ProductWishes */
export const GET_PRODUCT_WISHES_LIST = "GET_PRODUCT_WISHES_LIST";
export const GET_PRODUCT_WISHES_LOADING = "GET_PRODUCT_WISHES_LOADING";

/** MyOrders */
export const GET_MY_ORDERS_LIST = "GET_MY_ORDERS_LIST";
export const GET_MY_ORDERS_LOADING = "GET_MY_ORDERS_LOADING";

/** Wallets */
export const GET_WALLETS_LIST = "GET_WALLETS_LIST";
export const GET_WALLETS_LOADING = "GET_WALLETS_LOADING";

/** Home Page */
export const GET_HOMEPAGE_CATEGORY_LOADING = "GET_HOMEPAGE_CATEGORY_LOADING";
export const GET_HOMEPAGE_CATEGORY = "GET_HOMEPAGE_CATEGORY";

/** Notifications */
export const GET_NOTIFICATIONS_LIST = "GET_NOTIFICATIONS_LIST";
export const GET_NOTIFICATIONS_LOADING = "GET_NOTIFICATIONS_LOADING";
/**Place Orders */
export const ORDER_INPUT_CHANGE = "ORDER_INPUT_CHANGE";
export const ORDER_SUBMIT = "ORDER_SUBMIT";
export const ORDER_SUBMITTING = "ORDER_SUBMITTING";

/** Audience Poll */
export const GET_AUDIENCE_POLL = "GET_AUDIENCE_POLL";
export const GET_AUDIENCE_POLL_LOADING = "GET_AUDIENCE_POLL_LOADING";
// ******************************Product Filter**********************************/
export const CHANGE_PRODUCT_FILTER = "CHANGE_PRODUCT_FILTER";
export const GET_CATEGORIES_LIST = "GET_CATEGORIES_LIST";
export const GET_BRANDS_LIST_DATA = "GET_BRANDS_LIST_DATA";

//**********************************User**************************************** */
export const CHANGE_USER_INPUT_DATA = "CHANGE_USER_INPUT_DATA";
export const UPDATED_USER_DATA = "UPDATED_USER_DATA";
